### ISSUE TITLE
config file doesnt work

### ISSUE THREAD

**Issue by BerkantErbey** [hats-np/avis-imgv#10]
Hello,

Thanks for project. It's fast & simple.

In installation script (install.sh)

`if [ ! -f $config_dir/config.json ]; then
    echo "Configuration doesn't exist yet -> creating base configuration"
    mkdir -p $config_dir  
    cp ./examples/config.json $config_dir/config.json
fi`

but there is no config.json in examples directory. It's config.yaml
I copied config.yaml to config.json (not work)

As a result no context menu, no shortcuts.

**Comment by hats-np** [comment]
Hello! 
Thanks for your feedback. This is a bug from when I switched from yaml to json and forgot to update the example. It should be good now.
