### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by Maytha8** [hats-np/avis-imgv#8]
Hi there,
It would make it much easier to install if avis-imgv was available on crates.io, as `cargo install avis-imgv` can be used to install it quickly and cleanly if done so, rather than building from source.
I'm also asking for this because there has been [some interest in getting avis-imgv packaged in Debian](https://bugs.debian.org/1056319), but in order to do so, this needs to be published to crates.io first.
Thanks!

**Comment by hats-np** [comment]
Hello, 

that sounds good to me. 

I still need to improve the documentation and default shortcuts a bit, but I'll work on it and then publish to crates.io. 

Thanks for letting me know about the interest in getting it packaged in Debian. :)

**Comment by hatsnp** [comment]
It's published at: https://crates.io/crates/avis-imgv

**Comment by hats-np** [comment]
It's published at: https://crates.io/crates/avis-imgv

Did some quick testes and seems to be working fine with 'cargo install avis-imgv'.
